name:                AofC2018
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/AofC2018#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
  - TemplateHaskell
  - BangPatterns
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - containers
  - mtl
  - transformers
  - text
  - vector
  - megaparsec
  - void
  - lens
  - recursion-schemes

executables:
  AofC2018:
    source-dirs:      src
    main:             Main.hs
